<?php
/**
 * ChargeTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\finance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\finance;

use PHPUnit\Framework\TestCase;

/**
 * ChargeTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the charge container, which is an array of one or more charges related to the transfer.
 * @package     macropage\SDKs\ebay\rest\finance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ChargeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Charge"
     */
    public function testCharge()
    {
    }

    /**
     * Test attribute "cancellationId"
     */
    public function testPropertyCancellationId()
    {
    }

    /**
     * Test attribute "caseId"
     */
    public function testPropertyCaseId()
    {
    }

    /**
     * Test attribute "chargeNetAmount"
     */
    public function testPropertyChargeNetAmount()
    {
    }

    /**
     * Test attribute "inquiryId"
     */
    public function testPropertyInquiryId()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "paymentDisputeId"
     */
    public function testPropertyPaymentDisputeId()
    {
    }

    /**
     * Test attribute "refundId"
     */
    public function testPropertyRefundId()
    {
    }

    /**
     * Test attribute "returnId"
     */
    public function testPropertyReturnId()
    {
    }
}
