<?php
/**
 * OrderLineItemTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\finance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\finance;

use PHPUnit\Framework\TestCase;

/**
 * OrderLineItemTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to show the fees that are deducted from a seller payout for each line item in an order.
 * @package     macropage\SDKs\ebay\rest\finance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderLineItemTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderLineItem"
     */
    public function testOrderLineItem()
    {
    }

    /**
     * Test attribute "feeBasisAmount"
     */
    public function testPropertyFeeBasisAmount()
    {
    }

    /**
     * Test attribute "lineItemId"
     */
    public function testPropertyLineItemId()
    {
    }

    /**
     * Test attribute "marketplaceFees"
     */
    public function testPropertyMarketplaceFees()
    {
    }
}
