<?php
/**
 * TransactionSummaryResponseTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\finance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\finance;

use PHPUnit\Framework\TestCase;

/**
 * TransactionSummaryResponseTest Class Doc Comment
 *
 * @category    Class
 * @description This type is the base response type of the getTransactionSummary method, and based on the filters that are used in the getTransactionSummary call URI, the response may include total count and amount of the seller&#39;s sales and credits, total count and amount of buyer refunds, and total count and amount of seller payment holds.
 * @package     macropage\SDKs\ebay\rest\finance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionSummaryResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "TransactionSummaryResponse"
     */
    public function testTransactionSummaryResponse()
    {
    }

    /**
     * Test attribute "creditAmount"
     */
    public function testPropertyCreditAmount()
    {
    }

    /**
     * Test attribute "creditBookingEntry"
     */
    public function testPropertyCreditBookingEntry()
    {
    }

    /**
     * Test attribute "creditCount"
     */
    public function testPropertyCreditCount()
    {
    }

    /**
     * Test attribute "disputeAmount"
     */
    public function testPropertyDisputeAmount()
    {
    }

    /**
     * Test attribute "disputeBookingEntry"
     */
    public function testPropertyDisputeBookingEntry()
    {
    }

    /**
     * Test attribute "disputeCount"
     */
    public function testPropertyDisputeCount()
    {
    }

    /**
     * Test attribute "onHoldAmount"
     */
    public function testPropertyOnHoldAmount()
    {
    }

    /**
     * Test attribute "onHoldBookingEntry"
     */
    public function testPropertyOnHoldBookingEntry()
    {
    }

    /**
     * Test attribute "onHoldCount"
     */
    public function testPropertyOnHoldCount()
    {
    }

    /**
     * Test attribute "refundAmount"
     */
    public function testPropertyRefundAmount()
    {
    }

    /**
     * Test attribute "refundBookingEntry"
     */
    public function testPropertyRefundBookingEntry()
    {
    }

    /**
     * Test attribute "refundCount"
     */
    public function testPropertyRefundCount()
    {
    }

    /**
     * Test attribute "shippingLabelAmount"
     */
    public function testPropertyShippingLabelAmount()
    {
    }

    /**
     * Test attribute "shippingLabelBookingEntry"
     */
    public function testPropertyShippingLabelBookingEntry()
    {
    }

    /**
     * Test attribute "shippingLabelCount"
     */
    public function testPropertyShippingLabelCount()
    {
    }

    /**
     * Test attribute "transferAmount"
     */
    public function testPropertyTransferAmount()
    {
    }

    /**
     * Test attribute "transferBookingEntry"
     */
    public function testPropertyTransferBookingEntry()
    {
    }

    /**
     * Test attribute "transferCount"
     */
    public function testPropertyTransferCount()
    {
    }
}
