<?php
/**
 * TransferTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\finance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\finance;

use PHPUnit\Framework\TestCase;

/**
 * TransferTest Class Doc Comment
 *
 * @category    Class
 * @description This type is the base response type used by TRANSFER transaction type that is returned in the response.
 * @package     macropage\SDKs\ebay\rest\finance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransferTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Transfer"
     */
    public function testTransfer()
    {
    }

    /**
     * Test attribute "fundingSource"
     */
    public function testPropertyFundingSource()
    {
    }

    /**
     * Test attribute "transactionDate"
     */
    public function testPropertyTransactionDate()
    {
    }

    /**
     * Test attribute "transferAmount"
     */
    public function testPropertyTransferAmount()
    {
    }

    /**
     * Test attribute "transferDetail"
     */
    public function testPropertyTransferDetail()
    {
    }

    /**
     * Test attribute "transferId"
     */
    public function testPropertyTransferId()
    {
    }
}
