<?php
/**
 * TransactionTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  macropage\SDKs\ebay\rest\finance
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eBay Finances API
 *
 * This API is used to retrieve seller payouts and monetary transaction details related to those payouts.
 *
 * The version of the OpenAPI document: 1.4.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace macropage\SDKs\ebay\rest\finance;

use PHPUnit\Framework\TestCase;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to express the details of one of the following monetary transactions: a buyer&#39;s payment for an order, a refund to the buyer for a returned item or cancelled order, or a credit issued by eBay to the seller&#39;s account.
 * @package     macropage\SDKs\ebay\rest\finance
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class TransactionTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "bookingEntry"
     */
    public function testPropertyBookingEntry()
    {
    }

    /**
     * Test attribute "buyer"
     */
    public function testPropertyBuyer()
    {
    }

    /**
     * Test attribute "orderId"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "orderLineItems"
     */
    public function testPropertyOrderLineItems()
    {
    }

    /**
     * Test attribute "paymentsEntity"
     */
    public function testPropertyPaymentsEntity()
    {
    }

    /**
     * Test attribute "payoutId"
     */
    public function testPropertyPayoutId()
    {
    }

    /**
     * Test attribute "salesRecordReference"
     */
    public function testPropertySalesRecordReference()
    {
    }

    /**
     * Test attribute "totalFeeBasisAmount"
     */
    public function testPropertyTotalFeeBasisAmount()
    {
    }

    /**
     * Test attribute "totalFeeAmount"
     */
    public function testPropertyTotalFeeAmount()
    {
    }

    /**
     * Test attribute "transactionDate"
     */
    public function testPropertyTransactionDate()
    {
    }

    /**
     * Test attribute "transactionId"
     */
    public function testPropertyTransactionId()
    {
    }

    /**
     * Test attribute "transactionMemo"
     */
    public function testPropertyTransactionMemo()
    {
    }

    /**
     * Test attribute "transactionStatus"
     */
    public function testPropertyTransactionStatus()
    {
    }

    /**
     * Test attribute "transactionType"
     */
    public function testPropertyTransactionType()
    {
    }
}
